"""add sample_set

Revision ID: 59055cc1934f
Revises:
Create Date: 2020-02-28 12:11:31.732694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59055cc1934f'
down_revision = None
branch_labels = ('sample_db',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_set',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('luc_classification_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['luc_classification_system_id'], ['lccs.class_systems.id'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='sample_db'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_set', schema='sample_db')
    # ### end Alembic commands ###
