"""add oauth

Revision ID: 9e3b454df2df
Revises: f28c3fd2a06f
Create Date: 2020-03-05 11:11:24.741649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3b454df2df'
down_revision = 'f28c3fd2a06f'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_set', sa.Column('oauth', sa.String(), nullable=True), schema='sample_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_set', 'oauth', schema='sample_db')
    # ### end Alembic commands ###
